SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `STPAULS` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `STPAULS` ;

-- -----------------------------------------------------
-- Table `STPAULS`.`SUBJECT_CATEGORY`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`SUBJECT_CATEGORY` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  `CREATED_DATE` DATE NULL ,
  `CREATED_BY` VARCHAR(45) NULL ,
  `UPDATED_DATE` DATE NULL ,
  `UPDATED_BY` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAEM_UNIQUE` (`NAME` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`SUBJECT`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`SUBJECT` (
  `ID` INT NOT NULL ,
  `NAME` MEDIUMTEXT NULL ,
  `CREDIT` INT NULL ,
  `CREATED_BY` VARCHAR(45) NULL ,
  `CREATED_DATE` DATE NULL ,
  `UPDATED_BY` VARCHAR(45) NULL ,
  `UPDATED_DATE` DATE NULL ,
  `SUBJECT_CATEGORY_ID` INT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_SUBJECT_SUBJECT_CATEGORY_idx` (`SUBJECT_CATEGORY_ID` ASC) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) ,
  CONSTRAINT `fk_SUBJECT_SUBJECT_CATEGORY`
    FOREIGN KEY (`SUBJECT_CATEGORY_ID` )
    REFERENCES `STPAULS`.`SUBJECT_CATEGORY` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`SYLLABUS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`SYLLABUS` (
  `ID` INT NOT NULL ,
  `YEAR` INT NULL ,
  `TYPE` VARCHAR(45) NULL ,
  `SEMASTER` INT NULL ,
  `CREATED_BY` VARCHAR(45) NULL ,
  `CREATED_DATE` DATE NULL ,
  `UPDATED_BY` VARCHAR(45) NULL ,
  `UPDATED_DATE` DATE NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`BATCH`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`BATCH` (
  `ID` INT NOT NULL ,
  `YEAR` INT NULL ,
  `TYPE` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`CONGREGATION`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`CONGREGATION` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `CREATED_BY` VARCHAR(45) NOT NULL ,
  `CREATED_DATE` DATE NOT NULL ,
  `UPDATED_BY` VARCHAR(45) NULL ,
  `UPDATED_DATE` DATE NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`DIOCESE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`DIOCESE` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `CREATED_BY` VARCHAR(45) NOT NULL ,
  `CREATED_DATE` DATE NOT NULL ,
  `UPDATED_BY` VARCHAR(45) NULL ,
  `UPDATED_DATE` DATE NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`STUDENT`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`STUDENT` (
  `ID` INT NOT NULL ,
  `REG_NO` INT NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  `GENDER` VARCHAR(45) NOT NULL ,
  `DATE_OF_BIRTH` DATE NOT NULL ,
  `PLACE_OF_BIRTH` VARCHAR(45) NULL ,
  `REMARKS` VARCHAR(45) NULL ,
  `DATE_OF_JOINING` DATE NULL ,
  `FATHER_NAME` VARCHAR(45) NULL ,
  `MOTHER_NAME` VARCHAR(45) NULL ,
  `FATHER_OCCUPATION` VARCHAR(45) NULL ,
  `MOTHER_OCCUPATION` VARCHAR(45) NULL ,
  `CONTACT_NUMBER` INT NULL ,
  `DATE_OF_BAPTISM` DATE NULL ,
  `PLACE_OF_BAPTISM` VARCHAR(45) NULL ,
  `DATE_OF_CONFIRMATION` DATE NULL ,
  `PLACE_OF_CONFIRMATION` VARCHAR(45) NULL ,
  `FATHER_LIVING` TINYINT(1) NULL ,
  `MOTHER_LIVING` TINYINT(1) NULL ,
  `NO_OF_ELDER_BROTHER` INT NULL ,
  `NO_OF_YOUNGER_BROTHER` INT NULL ,
  `NO_OF_ELDER_SISTER` INT NULL ,
  `NO_OF_YOUNGER_SISTER` INT NULL ,
  `PARISH` VARCHAR(45) NULL ,
  `VILLAGE` VARCHAR(45) NULL ,
  `DIO_CONG_LAY` VARCHAR(45) NULL ,
  `NAME_OF_DIO_CONG` VARCHAR(45) NULL ,
  `MINOR_SEMINARY_NAME` VARCHAR(45) NULL ,
  `MINOR_SEMINARY_FROM_DATE` DATE NULL ,
  `MINOR_SEMINARY_TO_DATE` DATE NULL ,
  `DEGREE_COURSE` VARCHAR(45) NULL ,
  `DEGREE_COLLEGE` VARCHAR(45) NULL ,
  `DEGREE_FROM_DATE` DATE NULL ,
  `DEGREE_TO_DATE` DATE NULL ,
  `PHILOSOPHY_SEMINARY` VARCHAR(45) NULL ,
  `PHILOSOPHY_FROM_DATE` DATE NULL ,
  `PHILOSOPHY_TO_DATE` DATE NULL ,
  `REGENCY_PARISH` VARCHAR(45) NULL ,
  `REGENCY_FROM_DATE` DATE NULL ,
  `REGENCY_TO_DATE` DATE NULL ,
  `SPIRITUALITY_SEMINARY` VARCHAR(45) NULL ,
  `SPIRITUALITY_FROM_DATE` DATE NULL ,
  `SPIRITUALITY_TO_DATE` DATE NULL ,
  `CREATED_BY` VARCHAR(45) NOT NULL ,
  `CREATED_DATE` DATE NOT NULL ,
  `UPDATED_BY` VARCHAR(45) NULL ,
  `UPDATED_DATE` DATE NULL ,
  `BATCH_ID` INT NULL ,
  `CONGREGATION_ID` INT NULL ,
  `DIOCESE_ID` INT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) ,
  UNIQUE INDEX `REG_NO_UNIQUE` (`REG_NO` ASC) ,
  INDEX `fk_STUDENT_BATCH1_idx` (`BATCH_ID` ASC) ,
  INDEX `fk_STUDENT_CONGREGATION1_idx` (`CONGREGATION_ID` ASC) ,
  INDEX `fk_STUDENT_DIOCESE1_idx` (`DIOCESE_ID` ASC) ,
  CONSTRAINT `fk_STUDENT_BATCH1`
    FOREIGN KEY (`BATCH_ID` )
    REFERENCES `STPAULS`.`BATCH` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STUDENT_CONGREGATION1`
    FOREIGN KEY (`CONGREGATION_ID` )
    REFERENCES `STPAULS`.`CONGREGATION` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STUDENT_DIOCESE1`
    FOREIGN KEY (`DIOCESE_ID` )
    REFERENCES `STPAULS`.`DIOCESE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`MARK`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`MARK` (
  `ID` INT NOT NULL ,
  `MARK` DECIMAL(10,2) NULL ,
  `CREATED_BY` VARCHAR(45) NULL ,
  `CREATED_DATE` DATE NULL ,
  `UPDATED_BY` VARCHAR(45) NULL ,
  `UPDATED_DATE` DATE NULL ,
  `SUBJECT_ID` INT NULL ,
  `SYLLABUS_ID` INT NULL ,
  `STUDENT_ID` INT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_MARK_SUBJECT1_idx` (`SUBJECT_ID` ASC) ,
  INDEX `fk_MARK_SYLABUS1_idx` (`SYLLABUS_ID` ASC) ,
  INDEX `fk_MARK_STUDENT1_idx` (`STUDENT_ID` ASC) ,
  CONSTRAINT `fk_MARK_SUBJECT1`
    FOREIGN KEY (`SUBJECT_ID` )
    REFERENCES `STPAULS`.`SUBJECT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MARK_SYLABUS1`
    FOREIGN KEY (`SYLLABUS_ID` )
    REFERENCES `STPAULS`.`SYLLABUS` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MARK_STUDENT1`
    FOREIGN KEY (`STUDENT_ID` )
    REFERENCES `STPAULS`.`STUDENT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`SYLABUS_SUBJECT`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`SYLABUS_SUBJECT` (
  `SYLABUS_ID` INT NOT NULL ,
  `SUBJECT_ID` INT NOT NULL ,
  PRIMARY KEY (`SYLABUS_ID`, `SUBJECT_ID`) ,
  INDEX `fk_SYLABUS_has_SUBJECT_SUBJECT1_idx` (`SUBJECT_ID` ASC) ,
  INDEX `fk_SYLABUS_has_SUBJECT_SYLABUS1_idx` (`SYLABUS_ID` ASC) ,
  CONSTRAINT `fk_SYLABUS_has_SUBJECT_SYLABUS1`
    FOREIGN KEY (`SYLABUS_ID` )
    REFERENCES `STPAULS`.`SYLLABUS` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SYLABUS_has_SUBJECT_SUBJECT1`
    FOREIGN KEY (`SUBJECT_ID` )
    REFERENCES `STPAULS`.`SUBJECT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`ADDRESS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`ADDRESS` (
  `ID` INT NOT NULL ,
  `STREET` VARCHAR(250) NULL ,
  `CITY` VARCHAR(45) NULL ,
  `STATE` VARCHAR(45) NULL ,
  `COUNTRY` VARCHAR(45) NULL ,
  `PINCODE` INT(6) NULL ,
  `STUDENT_ID` INT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_ADDRESS_STUDENT1_idx` (`STUDENT_ID` ASC) ,
  CONSTRAINT `fk_ADDRESS_STUDENT1`
    FOREIGN KEY (`STUDENT_ID` )
    REFERENCES `STPAULS`.`STUDENT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`CONFIGURATION`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`CONFIGURATION` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `TYPE` VARCHAR(45) NULL ,
  `SUB_TYPE` VARCHAR(45) NULL ,
  `STATUS` TINYINT(1) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`Ministry`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`Ministry` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME_OF_MINISTRY` VARCHAR(45) NULL ,
  `MINISTRY_STATUS` TINYINT(1) NULL ,
  `STUDENT_ID` INT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_Ministry_STUDENT1_idx` (`STUDENT_ID` ASC) ,
  CONSTRAINT `fk_Ministry_STUDENT1`
    FOREIGN KEY (`STUDENT_ID` )
    REFERENCES `STPAULS`.`STUDENT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`DOCUMENT_STATUS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`DOCUMENT_STATUS` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `DOCUMENT_NAME` VARCHAR(45) NULL ,
  `DOCUMENT_STATUS` TINYINT(1) NULL ,
  `STUDENT_ID` INT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_DOCUMENT_STATUS_STUDENT1_idx` (`STUDENT_ID` ASC) ,
  CONSTRAINT `fk_DOCUMENT_STATUS_STUDENT1`
    FOREIGN KEY (`STUDENT_ID` )
    REFERENCES `STPAULS`.`STUDENT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`Book`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`Book` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NOT NULL ,
  `FREQUENCY` VARCHAR(45) NULL ,
  `AUTHOR` VARCHAR(45) NULL ,
  `PUBLISHING_DATE` DATE NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`SUBSCRIBER`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`SUBSCRIBER` (
  `ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `MOBILE_NUMBER` VARCHAR(45) NULL ,
  `STREET` VARCHAR(250) NULL ,
  `CITY` VARCHAR(45) NULL ,
  `STATE` VARCHAR(45) NULL ,
  `COUNTRY` VARCHAR(45) NULL ,
  `PINCODE` INT(6) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`SUBSCRIBE_INFO`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`SUBSCRIBE_INFO` (
  `ID` INT NOT NULL ,
  `NO_OF_YEAR` INT NULL ,
  `START_DATE` DATE NULL ,
  `END_DATE` DATE NULL ,
  `SUBSCRIBER_ID` INT NOT NULL ,
  `Book_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_SUBSCRIBE_INFO_SUBSCRIBER1_idx` (`SUBSCRIBER_ID` ASC) ,
  INDEX `fk_SUBSCRIBE_INFO_Book1_idx` (`Book_ID` ASC) ,
  CONSTRAINT `fk_SUBSCRIBE_INFO_SUBSCRIBER1`
    FOREIGN KEY (`SUBSCRIBER_ID` )
    REFERENCES `STPAULS`.`SUBSCRIBER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUBSCRIBE_INFO_Book1`
    FOREIGN KEY (`Book_ID` )
    REFERENCES `STPAULS`.`Book` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`GROUP_ST`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`GROUP_ST` (
  `ID` INT NOT NULL ,
  `GROUP_NAME` VARCHAR(45) NULL ,
  `STATUS` TINYINT(1) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`SHOP`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`SHOP` (
  `ID` INT NOT NULL ,
  `SHOP_NUMBER` VARCHAR(45) NULL ,
  `SQARE_FEET` DOUBLE NULL ,
  `GROUP_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_SHOP_GROUP1_idx` (`GROUP_ID` ASC) ,
  CONSTRAINT `fk_SHOP_GROUP1`
    FOREIGN KEY (`GROUP_ID` )
    REFERENCES `STPAULS`.`GROUP_ST` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`TENANT`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`TENANT` (
  `ID` INT NOT NULL ,
  `SHOP_NAME` VARCHAR(45) NULL ,
  `YEAR` INT NULL ,
  `PAYMENT_MODE` VARCHAR(45) NULL ,
  `PAYMENT_AMOUNT` DOUBLE NULL ,
  `SHOP_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_TENANT_SHOP1_idx` (`SHOP_ID` ASC) ,
  CONSTRAINT `fk_TENANT_SHOP1`
    FOREIGN KEY (`SHOP_ID` )
    REFERENCES `STPAULS`.`SHOP` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`ADDRESS_RENT`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`ADDRESS_RENT` (
  `ID` INT NOT NULL ,
  `STREET` VARCHAR(45) NULL ,
  `CITY` VARCHAR(45) NULL ,
  `STATE` VARCHAR(45) NULL ,
  `COUNTRY` VARCHAR(45) NULL ,
  `PINCODE` VARCHAR(45) NULL ,
  `TENANT_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_ADDRESS_RENT_TENANT1_idx` (`TENANT_ID` ASC) ,
  CONSTRAINT `fk_ADDRESS_RENT_TENANT1`
    FOREIGN KEY (`TENANT_ID` )
    REFERENCES `STPAULS`.`TENANT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STPAULS`.`SCHEDULER`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `STPAULS`.`SCHEDULER` (
  `ID` INT NOT NULL ,
  `BOOKING_DATE` DATE NULL ,
  `EXPIRY_DATE` DATE NULL ,
  `FROM_DATE` DATE NULL ,
  `TO_DATE` DATE NULL ,
  `DUE_DATE` DATE NULL ,
  `DAYS` INT NULL ,
  `DUE_AMOUNT` DOUBLE NULL ,
  `SERVICE_TAX` DOUBLE NULL ,
  `TAX_AMOUNT` DOUBLE NULL ,
  `TOTAL_DUE` DOUBLE NULL ,
  `PAYMENT_AMOUNT` DOUBLE NULL ,
  `PAYMENT_DATE` DATE NULL ,
  `TENANT_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `fk_SCHEDULER_TENANT1_idx` (`TENANT_ID` ASC) ,
  CONSTRAINT `fk_SCHEDULER_TENANT1`
    FOREIGN KEY (`TENANT_ID` )
    REFERENCES `STPAULS`.`TENANT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `STPAULS` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
