/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fixent.sm.client.student.view;

/**
 *
 * @author Mathan
 */
public class StudentDashboardView extends javax.swing.JPanel {

    /**
     * Creates new form StudentDashboardView
     */
    public StudentDashboardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        dioceseLabel = new javax.swing.JLabel();
        dioceseTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        nameLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        nameLabel.setText("Student Name");

        nameTextField.setMaximumSize(new java.awt.Dimension(6, 20));

        dioceseLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        dioceseLabel.setText("Student Diocese");

        dioceseTextField.setMaximumSize(new java.awt.Dimension(6, 20));

        searchButton.setBackground(new java.awt.Color(61, 86, 109));
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");

        addButton.setBackground(new java.awt.Color(61, 86, 109));
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add");
        addButton.setMaximumSize(new java.awt.Dimension(65, 23));
        addButton.setMinimumSize(new java.awt.Dimension(65, 23));
        addButton.setPreferredSize(new java.awt.Dimension(65, 23));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Student Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(dioceseLabel))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dioceseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dioceseLabel)
                    .addComponent(dioceseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(searchButton)
                .addGap(18, 18, 18)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel dioceseLabel;
    private javax.swing.JTextField dioceseTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JButton getAddButton() {
		return addButton;
	}

	public void setAddButton(javax.swing.JButton addButton) {
		this.addButton = addButton;
	}

	public javax.swing.JLabel getDioceseLabel() {
		return dioceseLabel;
	}

	public void setDioceseLabel(javax.swing.JLabel dioceseLabel) {
		this.dioceseLabel = dioceseLabel;
	}

	public javax.swing.JTextField getDioceseTextField() {
		return dioceseTextField;
	}

	public void setDioceseTextField(javax.swing.JTextField dioceseTextField) {
		this.dioceseTextField = dioceseTextField;
	}

	public javax.swing.JLabel getNameLabel() {
		return nameLabel;
	}

	public void setNameLabel(javax.swing.JLabel nameLabel) {
		this.nameLabel = nameLabel;
	}

	public javax.swing.JTextField getNameTextField() {
		return nameTextField;
	}

	public void setNameTextField(javax.swing.JTextField nameTextField) {
		this.nameTextField = nameTextField;
	}

	public javax.swing.JButton getSearchButton() {
		return searchButton;
	}

	public void setSearchButton(javax.swing.JButton searchButton) {
		this.searchButton = searchButton;
	}
    
    
}
