/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fixent.sm.client.student.view;

/**
 *
 * @author Mathan
 */
public class StudentView extends javax.swing.JPanel {

    /**
     * Creates new form StudentView
     */
    public StudentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        dobLabel = new javax.swing.JLabel();
        placeOfBirthLabel = new javax.swing.JLabel();
        placeOfBirthComboBox = new javax.swing.JComboBox();
        doBaptismLabel = new javax.swing.JLabel();
        poBaptismLabel = new javax.swing.JLabel();
        placeOfBaptismComboBox = new javax.swing.JComboBox();
        datOfConfirmationLabel = new javax.swing.JLabel();
        dateOfBirth = new com.fixent.sm.client.component.ADatePicker();
        dateOfBaptism = new com.fixent.sm.client.component.ADatePicker();
        dateOfConfirmation = new com.fixent.sm.client.component.ADatePicker();
        placeOfRegencyLabel = new javax.swing.JLabel();
        placeOfRegencyTextField = new javax.swing.JTextField();
        parentsLivingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        parentsNameLabel = new javax.swing.JLabel();
        parentsNameTextField = new javax.swing.JTextField();
        occupationOfParentsTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sistersTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        brothersTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        parentsLivingComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        parentsAddressTextField = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        secularStudiesLabel = new javax.swing.JLabel();
        secularStudiesTextField = new javax.swing.JTextField();
        minorSeminaryLabel = new javax.swing.JLabel();
        minorSeminaryTextField = new javax.swing.JTextField();
        majorSeminaryLabel = new javax.swing.JLabel();
        majorSeminaryTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        finalReportfromTheMajorSeminaryCheckBox = new javax.swing.JCheckBox();
        certificateOfPhilosophyCourseCheckBox = new javax.swing.JCheckBox();
        spirtiualYearFinalAssessmentCheckBox = new javax.swing.JCheckBox();
        regencyReportCheckBox = new javax.swing.JCheckBox();
        marriageCertificateOftheParentsCheckBox = new javax.swing.JCheckBox();
        baptismAndConfirmationCheckBox = new javax.swing.JCheckBox();
        degreeCertificateCheckBox = new javax.swing.JCheckBox();
        passportSizePhotoCheckBox = new javax.swing.JCheckBox();
        saveButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 204, 204))); // NOI18N

        nameLabel.setBackground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");

        typeLabel.setBackground(new java.awt.Color(255, 255, 255));
        typeLabel.setText("Type");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One", "Diocese", "Congregation" }));

        dobLabel.setBackground(new java.awt.Color(255, 255, 255));
        dobLabel.setText("Date of Birth");

        placeOfBirthLabel.setText("Place of Birth");

        placeOfBirthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One", "Kanchipuram", "Tiruvallur", "Cuddalore", "Villupuram", "Vellore", "Tiruvannamalai", "Salem", "Namakkal", "Dharmapuri", "Erode", "Coimbatore", "The Nilgiris", "Thanjavur", "Nagapattinam", "Tiruvarur", "Tiruchirappalli", "Karur", "Perambalur", "Pudukkottai", "Madurai", "Theni", "Dindigul", "Ramanathapuram", "Virudhunagar", "Sivagangai", "Tirunelveli", "Thoothukkudi", "Kanniyakumari", "Krishnagiri", "Ariyalur", "Tiruppur" }));
        placeOfBirthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOfBirthComboBoxActionPerformed(evt);
            }
        });

        doBaptismLabel.setBackground(new java.awt.Color(255, 255, 255));
        doBaptismLabel.setText("Date of Baptism");

        poBaptismLabel.setText("Place Of Baptism");

        placeOfBaptismComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One", "Kanchipuram", "Tiruvallur", "Cuddalore", "Villupuram", "Vellore", "Tiruvannamalai", "Salem", "Namakkal", "Dharmapuri", "Erode", "Coimbatore", "The Nilgiris", "Thanjavur", "Nagapattinam", "Tiruvarur", "Tiruchirappalli", "Karur", "Perambalur", "Pudukkottai", "Madurai", "Theni", "Dindigul", "Ramanathapuram", "Virudhunagar", "Sivagangai", "Tirunelveli", "Thoothukkudi", "Kanniyakumari", "Krishnagiri", "Ariyalur", "Tiruppur" }));

        datOfConfirmationLabel.setText("Date Of Confirmation");

        placeOfRegencyLabel.setText("Place Of Regency");

        parentsLivingLabel.setText("Parents Living");

        jLabel1.setText(" Address");

        parentsNameLabel.setText("Parents Name");

        jLabel4.setText("Occupation of the Parents");

        jLabel3.setText("No. of Sister's");

        jLabel2.setText("No. of Brother's");

        parentsLivingComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One", "Yes", "No" }));

        parentsAddressTextField.setColumns(20);
        parentsAddressTextField.setLineWrap(true);
        parentsAddressTextField.setRows(3);
        jScrollPane1.setViewportView(parentsAddressTextField);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datOfConfirmationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doBaptismLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOfConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOfBaptism, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poBaptismLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placeOfBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placeOfRegencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(placeOfBirthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placeOfBaptismComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placeOfRegencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parentsNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(parentsNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(brothersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(occupationOfParentsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(parentsLivingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(parentsLivingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sistersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placeOfBirthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placeOfBirthLabel))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placeOfBaptismComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poBaptismLabel))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placeOfRegencyLabel)
                            .addComponent(placeOfRegencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobLabel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(doBaptismLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(dateOfBaptism, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateOfConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datOfConfirmationLabel))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(parentsLivingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(sistersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parentsNameLabel)
                            .addComponent(parentsNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parentsLivingLabel))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(brothersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(occupationOfParentsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Educational Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(102, 204, 255))); // NOI18N

        secularStudiesLabel.setText("Secular Studies");

        minorSeminaryLabel.setText("Minor Seminary");

        majorSeminaryLabel.setText("Major Seminary");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secularStudiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(majorSeminaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(majorSeminaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(secularStudiesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(minorSeminaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(minorSeminaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secularStudiesLabel)
                    .addComponent(secularStudiesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minorSeminaryLabel)
                    .addComponent(minorSeminaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(majorSeminaryLabel)
                    .addComponent(majorSeminaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Documents to be Attached", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(153, 204, 255))); // NOI18N

        finalReportfromTheMajorSeminaryCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        finalReportfromTheMajorSeminaryCheckBox.setText("Final Report from the Major Seminary");

        certificateOfPhilosophyCourseCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        certificateOfPhilosophyCourseCheckBox.setText("Certificate of Philosopy Course");

        spirtiualYearFinalAssessmentCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        spirtiualYearFinalAssessmentCheckBox.setText("Spiritual Year Final Assessment");

        regencyReportCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        regencyReportCheckBox.setText("Regency Report");

        marriageCertificateOftheParentsCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        marriageCertificateOftheParentsCheckBox.setText("Marriage Certificate of theParents");

        baptismAndConfirmationCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        baptismAndConfirmationCheckBox.setText("Baptism & Confirmation");

        degreeCertificateCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        degreeCertificateCheckBox.setText("Degree Certificate");

        passportSizePhotoCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        passportSizePhotoCheckBox.setText("Passport Size Photo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(certificateOfPhilosophyCourseCheckBox)
                    .addComponent(finalReportfromTheMajorSeminaryCheckBox)
                    .addComponent(passportSizePhotoCheckBox))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spirtiualYearFinalAssessmentCheckBox)
                            .addComponent(degreeCertificateCheckBox))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regencyReportCheckBox)
                            .addComponent(baptismAndConfirmationCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(marriageCertificateOftheParentsCheckBox))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certificateOfPhilosophyCourseCheckBox)
                    .addComponent(spirtiualYearFinalAssessmentCheckBox)
                    .addComponent(baptismAndConfirmationCheckBox))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degreeCertificateCheckBox)
                    .addComponent(finalReportfromTheMajorSeminaryCheckBox)
                    .addComponent(regencyReportCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passportSizePhotoCheckBox)
                    .addComponent(marriageCertificateOftheParentsCheckBox))
                .addGap(38, 38, 38))
        );

        saveButton.setBackground(new java.awt.Color(153, 204, 255));
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Create");

        cancelBtn.setBackground(new java.awt.Color(153, 204, 255));
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelBtn))
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void placeOfBirthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOfBirthComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeOfBirthComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox baptismAndConfirmationCheckBox;
    private javax.swing.JTextField brothersTextField;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JCheckBox certificateOfPhilosophyCourseCheckBox;
    private javax.swing.JLabel datOfConfirmationLabel;
    private com.fixent.sm.client.component.ADatePicker dateOfBaptism;
    private com.fixent.sm.client.component.ADatePicker dateOfBirth;
    private com.fixent.sm.client.component.ADatePicker dateOfConfirmation;
    private javax.swing.JCheckBox degreeCertificateCheckBox;
    private javax.swing.JLabel doBaptismLabel;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JCheckBox finalReportfromTheMajorSeminaryCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel majorSeminaryLabel;
    private javax.swing.JTextField majorSeminaryTextField;
    private javax.swing.JCheckBox marriageCertificateOftheParentsCheckBox;
    private javax.swing.JLabel minorSeminaryLabel;
    private javax.swing.JTextField minorSeminaryTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField occupationOfParentsTextField;
    private javax.swing.JTextArea parentsAddressTextField;
    private javax.swing.JComboBox parentsLivingComboBox;
    private javax.swing.JLabel parentsLivingLabel;
    private javax.swing.JLabel parentsNameLabel;
    private javax.swing.JTextField parentsNameTextField;
    private javax.swing.JCheckBox passportSizePhotoCheckBox;
    private javax.swing.JComboBox placeOfBaptismComboBox;
    private javax.swing.JComboBox placeOfBirthComboBox;
    private javax.swing.JLabel placeOfBirthLabel;
    private javax.swing.JLabel placeOfRegencyLabel;
    private javax.swing.JTextField placeOfRegencyTextField;
    private javax.swing.JLabel poBaptismLabel;
    private javax.swing.JCheckBox regencyReportCheckBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel secularStudiesLabel;
    private javax.swing.JTextField secularStudiesTextField;
    private javax.swing.JTextField sistersTextField;
    private javax.swing.JCheckBox spirtiualYearFinalAssessmentCheckBox;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JCheckBox getBaptismAndConfirmationCheckBox() {
		return baptismAndConfirmationCheckBox;
	}

	public void setBaptismAndConfirmationCheckBox(
			javax.swing.JCheckBox baptismAndConfirmationCheckBox) {
		this.baptismAndConfirmationCheckBox = baptismAndConfirmationCheckBox;
	}

	

	public javax.swing.JCheckBox getCertificateOfPhilosophyCourseCheckBox() {
		return certificateOfPhilosophyCourseCheckBox;
	}

	public void setCertificateOfPhilosophyCourseCheckBox(
			javax.swing.JCheckBox certificateOfPhilosophyCourseCheckBox) {
		this.certificateOfPhilosophyCourseCheckBox = certificateOfPhilosophyCourseCheckBox;
	}

	public javax.swing.JLabel getDatOfConfirmationLabel() {
		return datOfConfirmationLabel;
	}

	public void setDatOfConfirmationLabel(javax.swing.JLabel datOfConfirmationLabel) {
		this.datOfConfirmationLabel = datOfConfirmationLabel;
	}

	public com.fixent.sm.client.component.ADatePicker getDateOfBaptism() {
		return dateOfBaptism;
	}

	public void setDateOfBaptism(
			com.fixent.sm.client.component.ADatePicker dateOfBaptism) {
		this.dateOfBaptism = dateOfBaptism;
	}

	public com.fixent.sm.client.component.ADatePicker getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(
			com.fixent.sm.client.component.ADatePicker dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public com.fixent.sm.client.component.ADatePicker getDateOfConfirmation() {
		return dateOfConfirmation;
	}

	public void setDateOfConfirmation(
			com.fixent.sm.client.component.ADatePicker dateOfConfirmation) {
		this.dateOfConfirmation = dateOfConfirmation;
	}

	public javax.swing.JCheckBox getDegreeCertificateCheckBox() {
		return degreeCertificateCheckBox;
	}

	public void setDegreeCertificateCheckBox(
			javax.swing.JCheckBox degreeCertificateCheckBox) {
		this.degreeCertificateCheckBox = degreeCertificateCheckBox;
	}

	public javax.swing.JLabel getDoBaptismLabel() {
		return doBaptismLabel;
	}

	public void setDoBaptismLabel(javax.swing.JLabel doBaptismLabel) {
		this.doBaptismLabel = doBaptismLabel;
	}

	public javax.swing.JLabel getDobLabel() {
		return dobLabel;
	}

	public void setDobLabel(javax.swing.JLabel dobLabel) {
		this.dobLabel = dobLabel;
	}

	public javax.swing.JCheckBox getFinalReportfromTheMajorSeminaryCheckBox() {
		return finalReportfromTheMajorSeminaryCheckBox;
	}

	public void setFinalReportfromTheMajorSeminaryCheckBox(
			javax.swing.JCheckBox finalReportfromTheMajorSeminaryCheckBox) {
		this.finalReportfromTheMajorSeminaryCheckBox = finalReportfromTheMajorSeminaryCheckBox;
	}

	public javax.swing.JTextField getMajorSeminaryTextField() {
		return majorSeminaryTextField;
	}

	public void setMajorSeminaryTextField(
			javax.swing.JTextField majorSeminaryTextField) {
		this.majorSeminaryTextField = majorSeminaryTextField;
	}

	public javax.swing.JCheckBox getMarriageCertificateOftheParentsCheckBox() {
		return marriageCertificateOftheParentsCheckBox;
	}

	public void setMarriageCertificateOftheParentsCheckBox(
			javax.swing.JCheckBox marriageCertificateOftheParentsCheckBox) {
		this.marriageCertificateOftheParentsCheckBox = marriageCertificateOftheParentsCheckBox;
	}

	public javax.swing.JTextField getMinorSeminaryTextField() {
		return minorSeminaryTextField;
	}

	public void setMinorSeminaryTextField(
			javax.swing.JTextField minorSeminaryTextField) {
		this.minorSeminaryTextField = minorSeminaryTextField;
	}

	public javax.swing.JTextField getNameTextField() {
		return nameTextField;
	}

	public void setNameTextField(javax.swing.JTextField nameTextField) {
		this.nameTextField = nameTextField;
	}

	public javax.swing.JCheckBox getPassportSizePhotoCheckBox() {
		return passportSizePhotoCheckBox;
	}

	public void setPassportSizePhotoCheckBox(
			javax.swing.JCheckBox passportSizePhotoCheckBox) {
		this.passportSizePhotoCheckBox = passportSizePhotoCheckBox;
	}

	public javax.swing.JComboBox getPlaceOfBaptismComboBox() {
		return placeOfBaptismComboBox;
	}

	public void setPlaceOfBaptismComboBox(
			javax.swing.JComboBox placeOfBaptismComboBox) {
		this.placeOfBaptismComboBox = placeOfBaptismComboBox;
	}

	public javax.swing.JComboBox getPlaceOfBirthComboBox() {
		return placeOfBirthComboBox;
	}

	public void setPlaceOfBirthComboBox(javax.swing.JComboBox placeOfBirthComboBox) {
		this.placeOfBirthComboBox = placeOfBirthComboBox;
	}

	public javax.swing.JTextField getPlaceOfRegencyTextField() {
		return placeOfRegencyTextField;
	}

	public void setPlaceOfRegencyTextField(
			javax.swing.JTextField placeOfRegencyTextField) {
		this.placeOfRegencyTextField = placeOfRegencyTextField;
	}

	public javax.swing.JCheckBox getRegencyReportCheckBox() {
		return regencyReportCheckBox;
	}

	public void setRegencyReportCheckBox(javax.swing.JCheckBox regencyReportCheckBox) {
		this.regencyReportCheckBox = regencyReportCheckBox;
	}

	public javax.swing.JButton getSaveButton() {
		return saveButton;
	}

	public void setSaveButton(javax.swing.JButton saveButton) {
		this.saveButton = saveButton;
	}

	public javax.swing.JTextField getSecularStudiesTextField() {
		return secularStudiesTextField;
	}

	public void setSecularStudiesTextField(
			javax.swing.JTextField secularStudiesTextField) {
		this.secularStudiesTextField = secularStudiesTextField;
	}

	public javax.swing.JCheckBox getSpirtiualYearFinalAssessmentCheckBox() {
		return spirtiualYearFinalAssessmentCheckBox;
	}

	public void setSpirtiualYearFinalAssessmentCheckBox(
			javax.swing.JCheckBox spirtiualYearFinalAssessmentCheckBox) {
		this.spirtiualYearFinalAssessmentCheckBox = spirtiualYearFinalAssessmentCheckBox;
	}

	public javax.swing.JComboBox getTypeComboBox() {
		return typeComboBox;
	}

	public void setTypeComboBox(javax.swing.JComboBox typeComboBox) {
		this.typeComboBox = typeComboBox;
	}

	
	public javax.swing.JPanel getjPanel1() {
		return jPanel1;
	}

	public void setjPanel1(javax.swing.JPanel jPanel1) {
		this.jPanel1 = jPanel1;
	}

	public javax.swing.JPanel getjPanel2() {
		return jPanel2;
	}

	public void setjPanel2(javax.swing.JPanel jPanel2) {
		this.jPanel2 = jPanel2;
	}

	public javax.swing.JPanel getjPanel3() {
		return jPanel3;
	}

	public void setjPanel3(javax.swing.JPanel jPanel3) {
		this.jPanel3 = jPanel3;
	}

	public javax.swing.JLabel getMajorSeminaryLabel() {
		return majorSeminaryLabel;
	}

	public void setMajorSeminaryLabel(javax.swing.JLabel majorSeminaryLabel) {
		this.majorSeminaryLabel = majorSeminaryLabel;
	}

	public javax.swing.JLabel getMinorSeminaryLabel() {
		return minorSeminaryLabel;
	}

	public void setMinorSeminaryLabel(javax.swing.JLabel minorSeminaryLabel) {
		this.minorSeminaryLabel = minorSeminaryLabel;
	}

	public javax.swing.JLabel getNameLabel() {
		return nameLabel;
	}

	public void setNameLabel(javax.swing.JLabel nameLabel) {
		this.nameLabel = nameLabel;
	}


	public javax.swing.JLabel getPlaceOfBirthLabel() {
		return placeOfBirthLabel;
	}

	public void setPlaceOfBirthLabel(javax.swing.JLabel placeOfBirthLabel) {
		this.placeOfBirthLabel = placeOfBirthLabel;
	}

	public javax.swing.JLabel getPlaceOfRegencyLabel() {
		return placeOfRegencyLabel;
	}

	public void setPlaceOfRegencyLabel(javax.swing.JLabel placeOfRegencyLabel) {
		this.placeOfRegencyLabel = placeOfRegencyLabel;
	}

	public javax.swing.JLabel getPoBaptismLabel() {
		return poBaptismLabel;
	}

	public void setPoBaptismLabel(javax.swing.JLabel poBaptismLabel) {
		this.poBaptismLabel = poBaptismLabel;
	}

	public javax.swing.JLabel getSecularStudiesLabel() {
		return secularStudiesLabel;
	}

	public void setSecularStudiesLabel(javax.swing.JLabel secularStudiesLabel) {
		this.secularStudiesLabel = secularStudiesLabel;
	}

	public javax.swing.JLabel getTypeLabel() {
		return typeLabel;
	}

	public void setTypeLabel(javax.swing.JLabel typeLabel) {
		this.typeLabel = typeLabel;
	}

	public javax.swing.JTextField getBrothersTextField() {
		return brothersTextField;
	}

	public void setBrothersTextField(javax.swing.JTextField brothersTextField) {
		this.brothersTextField = brothersTextField;
	}

	public javax.swing.JButton getCancelBtn() {
		return cancelBtn;
	}

	public void setCancelBtn(javax.swing.JButton cancelBtn) {
		this.cancelBtn = cancelBtn;
	}

	public javax.swing.JLabel getjLabel1() {
		return jLabel1;
	}

	public void setjLabel1(javax.swing.JLabel jLabel1) {
		this.jLabel1 = jLabel1;
	}

	public javax.swing.JLabel getjLabel2() {
		return jLabel2;
	}

	public void setjLabel2(javax.swing.JLabel jLabel2) {
		this.jLabel2 = jLabel2;
	}

	public javax.swing.JLabel getjLabel3() {
		return jLabel3;
	}

	public void setjLabel3(javax.swing.JLabel jLabel3) {
		this.jLabel3 = jLabel3;
	}

	public javax.swing.JLabel getjLabel4() {
		return jLabel4;
	}

	public void setjLabel4(javax.swing.JLabel jLabel4) {
		this.jLabel4 = jLabel4;
	}

	public javax.swing.JLabel getjLabel5() {
		return jLabel5;
	}

	public void setjLabel5(javax.swing.JLabel jLabel5) {
		this.jLabel5 = jLabel5;
	}

	public javax.swing.JScrollPane getjScrollPane1() {
		return jScrollPane1;
	}

	public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
		this.jScrollPane1 = jScrollPane1;
	}

	public javax.swing.JTextField getOccupationOfParentsTextField() {
		return occupationOfParentsTextField;
	}

	public void setOccupationOfParentsTextField(
			javax.swing.JTextField occupationOfParentsTextField) {
		this.occupationOfParentsTextField = occupationOfParentsTextField;
	}

	public javax.swing.JTextArea getParentsAddressTextField() {
		return parentsAddressTextField;
	}

	public void setParentsAddressTextField(
			javax.swing.JTextArea parentsAddressTextField) {
		this.parentsAddressTextField = parentsAddressTextField;
	}

	public javax.swing.JComboBox getParentsLivingComboBox() {
		return parentsLivingComboBox;
	}

	public void setParentsLivingComboBox(javax.swing.JComboBox parentsLivingComboBox) {
		this.parentsLivingComboBox = parentsLivingComboBox;
	}

	public javax.swing.JLabel getParentsLivingLabel() {
		return parentsLivingLabel;
	}

	public void setParentsLivingLabel(javax.swing.JLabel parentsLivingLabel) {
		this.parentsLivingLabel = parentsLivingLabel;
	}

	public javax.swing.JLabel getParentsNameLabel() {
		return parentsNameLabel;
	}

	public void setParentsNameLabel(javax.swing.JLabel parentsNameLabel) {
		this.parentsNameLabel = parentsNameLabel;
	}

	public javax.swing.JTextField getParentsNameTextField() {
		return parentsNameTextField;
	}

	public void setParentsNameTextField(javax.swing.JTextField parentsNameTextField) {
		this.parentsNameTextField = parentsNameTextField;
	}

	public javax.swing.JTextField getSistersTextField() {
		return sistersTextField;
	}

	public void setSistersTextField(javax.swing.JTextField sistersTextField) {
		this.sistersTextField = sistersTextField;
	}
	    
}
