/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fixent.sm.client.common;

/**
 *
 * @author Mathan
 */
public class ErrorMessageView extends javax.swing.JPanel {

    /**
     * Creates new form ErrorMessageView
     */
    public ErrorMessageView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageLabel = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));

        closeButton.setBackground(new java.awt.Color(255, 255, 255));
        closeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        closeButton.setText("X");
        closeButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        closeButton.setFocusPainted(false);
        closeButton.setOpaque(false);

        jScrollPane1.setBorder(null);

        messageLabel.setColumns(20);
        messageLabel.setRows(5);
        messageLabel.setBorder(null);
        messageLabel.setCaretColor(new java.awt.Color(255, 255, 255));
        messageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        messageLabel.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(messageLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageLabel;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JButton getCloseButton() {
		return closeButton;
	}

	public void setCloseButton(javax.swing.JButton closeButton) {
		this.closeButton = closeButton;
	}

	public javax.swing.JScrollPane getjScrollPane1() {
		return jScrollPane1;
	}

	public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
		this.jScrollPane1 = jScrollPane1;
	}

	public javax.swing.JTextArea getMessageLabel() {
		return messageLabel;
	}

	public void setMessageLabel(javax.swing.JTextArea messageLabel) {
		this.messageLabel = messageLabel;
	}
    
    

}
